import { relations, sql } from "drizzle-orm";
import {
  index,
  integer,
  sqliteTable,
  text,
  uniqueIndex,
} from "drizzle-orm/sqlite-core";

/**
 * Shop Manager schema — Turso / libSQL (SQLite).
 *
 * Money strategy: every monetary column stores INTEGER minor units
 * (cents). 12.50 EUR -> 1250. No floating point.
 * Timestamps: INTEGER unix epoch (seconds), mode: "timestamp".
 * IDs: TEXT UUID (crypto.randomUUID) generated by the app layer.
 */

const id = () =>
  text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID());

const createdAt = () =>
  integer("created_at", { mode: "timestamp" })
    .notNull()
    .default(sql`(unixepoch())`);

const updatedAt = () =>
  integer("updated_at", { mode: "timestamp" })
    .notNull()
    .default(sql`(unixepoch())`);

export const users = sqliteTable(
  "users",
  {
    id: id(),
    email: text("email").notNull(),
    passwordHash: text("password_hash").notNull(),
    name: text("name").notNull(),
    avatarUrl: text("avatar_url"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => ({
    emailIdx: uniqueIndex("users_email_idx").on(t.email),
  }),
);

export const sessions = sqliteTable(
  "sessions",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    expiresAt: integer("expires_at", { mode: "timestamp" }).notNull(),
  },
  (t) => ({
    userIdIdx: index("sessions_user_id_idx").on(t.userId),
  }),
);

export const stores = sqliteTable(
  "stores",
  {
    id: id(),
    ownerId: text("owner_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),
    name: text("name").notNull(),
    taxId: text("tax_id"),
    currency: text("currency").notNull().default("EUR"),
    timezone: text("timezone").notNull().default("Europe/Madrid"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => ({
    ownerIdIdx: index("stores_owner_id_idx").on(t.ownerId),
  }),
);

export const storeMembers = sqliteTable(
  "store_members",
  {
    id: id(),
    storeId: text("store_id")
      .notNull()
      .references(() => stores.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    role: text("role", { enum: ["owner", "admin", "employee"] })
      .notNull()
      .default("employee"),
    createdAt: createdAt(),
  },
  (t) => ({
    storeUserIdx: uniqueIndex("store_members_store_user_idx").on(
      t.storeId,
      t.userId,
    ),
    userIdIdx: index("store_members_user_id_idx").on(t.userId),
  }),
);

export const categories = sqliteTable(
  "categories",
  {
    id: id(),
    storeId: text("store_id")
      .notNull()
      .references(() => stores.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    type: text("type", { enum: ["product", "expense"] }).notNull(),
    createdAt: createdAt(),
  },
  (t) => ({
    storeIdIdx: index("categories_store_id_idx").on(t.storeId),
  }),
);

export const products = sqliteTable(
  "products",
  {
    id: id(),
    storeId: text("store_id")
      .notNull()
      .references(() => stores.id, { onDelete: "cascade" }),
    categoryId: text("category_id").references(() => categories.id, {
      onDelete: "set null",
    }),
    name: text("name").notNull(),
    sku: text("sku"),
    description: text("description"),
    imageUrl: text("image_url"),
    salePrice: integer("sale_price").notNull().default(0),
    costPrice: integer("cost_price").notNull().default(0),
    stock: integer("stock").notNull().default(0),
    minimumStock: integer("minimum_stock").notNull().default(0),
    active: integer("active", { mode: "boolean" }).notNull().default(true),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => ({
    storeIdIdx: index("products_store_id_idx").on(t.storeId),
    categoryIdIdx: index("products_category_id_idx").on(t.categoryId),
    storeSkuIdx: uniqueIndex("products_store_sku_idx").on(t.storeId, t.sku),
  }),
);

export const customers = sqliteTable(
  "customers",
  {
    id: id(),
    storeId: text("store_id")
      .notNull()
      .references(() => stores.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    email: text("email"),
    phone: text("phone"),
    notes: text("notes"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => ({
    storeIdIdx: index("customers_store_id_idx").on(t.storeId),
  }),
);

export const sales = sqliteTable(
  "sales",
  {
    id: id(),
    storeId: text("store_id")
      .notNull()
      .references(() => stores.id, { onDelete: "cascade" }),
    customerId: text("customer_id").references(() => customers.id, {
      onDelete: "set null",
    }),
    total: integer("total").notNull().default(0),
    taxAmount: integer("tax_amount").notNull().default(0),
    paymentMethod: text("payment_method"),
    status: text("status", { enum: ["completed", "cancelled"] })
      .notNull()
      .default("completed"),
    saleDate: integer("sale_date", { mode: "timestamp" })
      .notNull()
      .default(sql`(unixepoch())`),
    notes: text("notes"),
    createdAt: createdAt(),
  },
  (t) => ({
    storeIdIdx: index("sales_store_id_idx").on(t.storeId),
    customerIdIdx: index("sales_customer_id_idx").on(t.customerId),
    saleDateIdx: index("sales_sale_date_idx").on(t.saleDate),
    statusIdx: index("sales_status_idx").on(t.status),
  }),
);

export const saleItems = sqliteTable(
  "sale_items",
  {
    id: id(),
    saleId: text("sale_id")
      .notNull()
      .references(() => sales.id, { onDelete: "cascade" }),
    productId: text("product_id").references(() => products.id, {
      onDelete: "set null",
    }),
    quantity: integer("quantity").notNull(),
    unitPrice: integer("unit_price").notNull(),
    costPrice: integer("cost_price").notNull().default(0),
    subtotal: integer("subtotal").notNull(),
  },
  (t) => ({
    saleIdIdx: index("sale_items_sale_id_idx").on(t.saleId),
    productIdIdx: index("sale_items_product_id_idx").on(t.productId),
  }),
);

export const expenses = sqliteTable(
  "expenses",
  {
    id: id(),
    storeId: text("store_id")
      .notNull()
      .references(() => stores.id, { onDelete: "cascade" }),
    categoryId: text("category_id").references(() => categories.id, {
      onDelete: "set null",
    }),
    supplier: text("supplier"),
    description: text("description").notNull(),
    amount: integer("amount").notNull(),
    taxAmount: integer("tax_amount").notNull().default(0),
    paymentMethod: text("payment_method"),
    expenseDate: integer("expense_date", { mode: "timestamp" })
      .notNull()
      .default(sql`(unixepoch())`),
    notes: text("notes"),
    receiptUrl: text("receipt_url"),
    status: text("status", { enum: ["pending", "paid", "cancelled"] })
      .notNull()
      .default("paid"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => ({
    storeIdIdx: index("expenses_store_id_idx").on(t.storeId),
    categoryIdIdx: index("expenses_category_id_idx").on(t.categoryId),
    expenseDateIdx: index("expenses_expense_date_idx").on(t.expenseDate),
    statusIdx: index("expenses_status_idx").on(t.status),
  }),
);

export const inventoryMovements = sqliteTable(
  "inventory_movements",
  {
    id: id(),
    storeId: text("store_id")
      .notNull()
      .references(() => stores.id, { onDelete: "cascade" }),
    productId: text("product_id")
      .notNull()
      .references(() => products.id, { onDelete: "cascade" }),
    type: text("type", {
      enum: ["sale", "purchase", "adjustment", "return"],
    }).notNull(),
    quantity: integer("quantity").notNull(),
    referenceId: text("reference_id"),
    notes: text("notes"),
    createdAt: createdAt(),
  },
  (t) => ({
    storeIdIdx: index("inventory_movements_store_id_idx").on(t.storeId),
    productIdIdx: index("inventory_movements_product_id_idx").on(t.productId),
    typeIdx: index("inventory_movements_type_idx").on(t.type),
  }),
);

export const paymentMethods = sqliteTable(
  "payment_methods",
  {
    id: id(),
    storeId: text("store_id")
      .notNull()
      .references(() => stores.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    active: integer("active", { mode: "boolean" }).notNull().default(true),
    createdAt: createdAt(),
  },
  (t) => ({
    storeIdIdx: index("payment_methods_store_id_idx").on(t.storeId),
  }),
);

export const usersRelations = relations(users, ({ many }) => ({
  sessions: many(sessions),
  ownedStores: many(stores),
  memberships: many(storeMembers),
}));

export const sessionsRelations = relations(sessions, ({ one }) => ({
  user: one(users, { fields: [sessions.userId], references: [users.id] }),
}));

export const storesRelations = relations(stores, ({ one, many }) => ({
  owner: one(users, { fields: [stores.ownerId], references: [users.id] }),
  members: many(storeMembers),
  categories: many(categories),
  products: many(products),
  customers: many(customers),
  sales: many(sales),
  expenses: many(expenses),
  inventoryMovements: many(inventoryMovements),
  paymentMethods: many(paymentMethods),
}));

export const storeMembersRelations = relations(storeMembers, ({ one }) => ({
  store: one(stores, {
    fields: [storeMembers.storeId],
    references: [stores.id],
  }),
  user: one(users, {
    fields: [storeMembers.userId],
    references: [users.id],
  }),
}));

export const categoriesRelations = relations(categories, ({ one, many }) => ({
  store: one(stores, {
    fields: [categories.storeId],
    references: [stores.id],
  }),
  products: many(products),
  expenses: many(expenses),
}));

export const productsRelations = relations(products, ({ one, many }) => ({
  store: one(stores, { fields: [products.storeId], references: [stores.id] }),
  category: one(categories, {
    fields: [products.categoryId],
    references: [categories.id],
  }),
  saleItems: many(saleItems),
  inventoryMovements: many(inventoryMovements),
}));

export const customersRelations = relations(customers, ({ one, many }) => ({
  store: one(stores, {
    fields: [customers.storeId],
    references: [stores.id],
  }),
  sales: many(sales),
}));

export const salesRelations = relations(sales, ({ one, many }) => ({
  store: one(stores, { fields: [sales.storeId], references: [stores.id] }),
  customer: one(customers, {
    fields: [sales.customerId],
    references: [customers.id],
  }),
  items: many(saleItems),
}));

export const saleItemsRelations = relations(saleItems, ({ one }) => ({
  sale: one(sales, { fields: [saleItems.saleId], references: [sales.id] }),
  product: one(products, {
    fields: [saleItems.productId],
    references: [products.id],
  }),
}));

export const expensesRelations = relations(expenses, ({ one }) => ({
  store: one(stores, { fields: [expenses.storeId], references: [stores.id] }),
  category: one(categories, {
    fields: [expenses.categoryId],
    references: [categories.id],
  }),
}));

export const inventoryMovementsRelations = relations(
  inventoryMovements,
  ({ one }) => ({
    store: one(stores, {
      fields: [inventoryMovements.storeId],
      references: [stores.id],
    }),
    product: one(products, {
      fields: [inventoryMovements.productId],
      references: [products.id],
    }),
  }),
);

export const paymentMethodsRelations = relations(paymentMethods, ({ one }) => ({
  store: one(stores, {
    fields: [paymentMethods.storeId],
    references: [stores.id],
  }),
}));

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type Store = typeof stores.$inferSelect;
export type NewStore = typeof stores.$inferInsert;
export type StoreMember = typeof storeMembers.$inferSelect;
export type Category = typeof categories.$inferSelect;
export type Product = typeof products.$inferSelect;
export type NewProduct = typeof products.$inferInsert;
export type Customer = typeof customers.$inferSelect;
export type Sale = typeof sales.$inferSelect;
export type SaleItem = typeof saleItems.$inferSelect;
export type Expense = typeof expenses.$inferSelect;
export type InventoryMovement = typeof inventoryMovements.$inferSelect;
export type PaymentMethod = typeof paymentMethods.$inferSelect;
